//! Part and material segmentation for Albedo.
//!
//! Takes a mesh and answers "which bits of this are one thing", at every level
//! of coarseness at once. It does not decide how many parts the model has, and
//! that is on purpose: nothing about a rock sitting on a patch of ground says
//! whether the answer is two parts, or a rock and eleven tufts of grass. The
//! engine produces the whole hierarchy and lets the person looking at the model
//! pick the level, which they can do in a fraction of a second and it cannot.
//!
//! Written for the input that has no other tool: a mesh generated by
//! Hunyuan3D, Meshy or Tripo, which arrives as one shell, one material and one
//! UV atlas, with nothing anywhere in the file admitting it has parts at all.
//!
//! ## Where this sits against the literature
//!
//! The neural work is where the field is — PartField (ICCV 2025), P3-SAM,
//! SAMesh — and all of it wants PyTorch, a GPU and a few hundred megabytes of
//! weights. Albedo is a five megabyte executable that also has to start fast
//! enough to draw an Explorer thumbnail, so none of it can live in here.
//!
//! What is in here instead is the classical stack those papers benchmark
//! against, which is closer than the gap in publication dates suggests: on the
//! Princeton benchmark the Shape Diameter Function scores 0.175 against
//! Normalized Cuts' 0.172 while costing a thirty-fifth as much. Two departures
//! from it, both because of the input:
//!
//! - **Colour is a first class feature.** No classical benchmark uses it,
//!   because benchmark meshes are untextured. On a painted atlas it is the
//!   strongest signal there is, and often the only one.
//! - **The output is a hierarchy, not a partition.** Borrowed from PartField's
//!   final stage, and it is what makes the result something you steer rather
//!   than something you re-run.
//!
//! The neural route stays open from the other end: a per-face label array
//! produced by any of those models drops into the same display, editing and
//! splitting as a result computed here.

pub mod cluster;
pub mod features;
pub mod graph;

use std::time::Instant;

use retopo_core::{Adjacency, Mesh};
use serde::{Deserialize, Serialize};

pub use cluster::Dendrogram;
pub use features::{EdgeFeatures, FaceFeatures};
pub use graph::{Barriers, SegmentOptions, Weights};

/// What a run produced, and what it can say about itself.
#[derive(Clone, Debug, Default)]
pub struct Segmentation {
    pub dendrogram: Dendrogram,
    pub report: SegmentReport,
}

/// The numbers worth showing a person, and the two worth warning them about.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SegmentReport {
    pub triangles: usize,
    /// How many regions survived the pre-merge. The ceiling of the slider.
    pub superfaces: usize,
    pub merges: usize,
    /// The fewest groups reachable. Barriers make this more than one.
    pub floor: usize,
    /// Where to open the slider: the largest jump in the merge cost column.
    pub suggested: usize,

    /// Disconnected pieces of surface in the input.
    pub shells: usize,
    /// Charts in the atlas.
    pub uv_islands: usize,
    /// Material slots the file declared.
    pub materials: usize,

    /// False when no material carries a base colour texture, meaning the colour
    /// feature could only ever restate the material one. Worth saying out loud:
    /// it is the difference between a good result and a puzzling one, and the
    /// person looking at the model cannot tell from the viewport.
    pub colour_textured: bool,
    /// Edges with more than two triangles. Dihedral angles are unreliable
    /// wherever these are, which is worth a warning rather than a refusal.
    pub non_manifold_edges: usize,

    pub ms: u64,
}

/// Segment a mesh.
///
/// `progress` is called at stage boundaries rather than inside the loops. There
/// are four stages and the last two are the ones worth waiting through, so a
/// smooth bar here would be a lie told sixty times a second; four honest steps
/// say more.
pub fn segment(
    mesh: &Mesh,
    opts: &SegmentOptions,
    progress: &mut dyn FnMut(f32),
) -> Segmentation {
    let started = Instant::now();

    progress(0.0);
    let adj = Adjacency::build(mesh);
    progress(0.15);
    let ef = EdgeFeatures::build(mesh, &adj);
    progress(0.25);
    // Sampling the atlas six times per triangle is most of the wall clock on
    // anything with a texture, which is why the bar sits here for a while.
    let ff = FaceFeatures::build(mesh, &adj, &ef);
    progress(0.55);
    let dendrogram = cluster::build(mesh, &adj, &ff, &ef, opts);
    progress(1.0);

    let report = SegmentReport {
        triangles: mesh.triangle_count(),
        superfaces: dendrogram.super_count,
        merges: dendrogram.merges.len(),
        floor: dendrogram.floor,
        suggested: suggest(&dendrogram),
        shells: ff.shell_count,
        uv_islands: ff.uv_island_count,
        materials: mesh.materials.len(),
        colour_textured: ff.colour_is_textured,
        non_manifold_edges: adj.non_manifold_edges,
        ms: started.elapsed().as_millis() as u64,
    };

    Segmentation { dendrogram, report }
}

/// Where to open the slider.
///
/// The elbow: the point in the merge order where the next join suddenly costs
/// far more than the last one, which is the algorithm saying it has run out of
/// things that obviously belong together. Read from the *end* of the column
/// backwards, because that is where the few expensive merges that flatten a
/// model into two halves live, and searched only over a plausible range so that
/// one freak jump at merge three cannot propose four hundred groups.
fn suggest(d: &Dendrogram) -> usize {
    const MOST: usize = 48;

    let n = d.costs.len();
    if n == 0 {
        return d.super_count.max(1);
    }

    // Group counts of `floor..=MOST` correspond to the last stretch of merges.
    let lowest = d.floor.max(2);
    let highest = MOST.min(d.super_count).max(lowest);

    let mut best = (0.0f32, lowest);
    for k in lowest..=highest {
        // Cutting to `k` groups means taking `super_count - k` merges, so the
        // merge that would take us from `k` to `k - 1` sits at that index.
        let i = d.super_count.saturating_sub(k);
        if i == 0 || i >= n {
            continue;
        }
        let jump = d.costs[i] - d.costs[i - 1];
        if jump > best.0 {
            best = (jump, k);
        }
    }

    if best.0 > 0.0 {
        best.1
    } else {
        lowest
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use glam::{Vec2, Vec3};
    use retopo_core::mesh::{Image, Material};

    fn painted(bands: usize) -> Mesh {
        let quads = bands * 4;
        let mut m = Mesh {
            materials: vec![Material::default()],
            ..Default::default()
        };
        for i in 0..=quads {
            let x = i as f32;
            m.positions.push(Vec3::new(x, 0.0, 0.0));
            m.positions.push(Vec3::new(x, 1.0, 0.0));
            m.normals.push(Vec3::Z);
            m.normals.push(Vec3::Z);
            let u = i as f32 / quads as f32;
            m.uvs.push(Vec2::new(u, 0.0));
            m.uvs.push(Vec2::new(u, 1.0));
        }
        for i in 0..quads {
            let a = (i * 2) as u32;
            m.triangles.push([a, a + 2, a + 3]);
            m.triangles.push([a, a + 3, a + 1]);
            m.tri_material.extend([0, 0]);
        }
        m.rebuild_weld(0.0);

        let w = 32 * bands as u32;
        let mut img = Image::new(w, 1);
        for x in 0..w {
            let band = (x * bands as u32 / w).min(bands as u32 - 1);
            let v = (18 + band * (220 / bands.max(1) as u32)) as u8;
            let i = (x * 4) as usize;
            img.rgba[i] = v;
            img.rgba[i + 1] = v;
            img.rgba[i + 2] = v;
            img.rgba[i + 3] = 255;
        }
        m.images.push(img);
        m.materials[0].base_color_texture = Some(0);
        m
    }

    #[test]
    fn an_empty_mesh_is_survived_rather_than_panicked_on() {
        let s = segment(&Mesh::default(), &SegmentOptions::default(), &mut |_| {});
        assert_eq!(s.report.triangles, 0);
        assert_eq!(s.dendrogram.super_count, 0);
        assert!(s.dendrogram.cut(1).is_empty());
    }

    #[test]
    fn the_report_notices_an_untextured_model() {
        let mut m = painted(3);
        m.materials[0].base_color_texture = None;
        m.images.clear();
        let s = segment(&m, &SegmentOptions::default(), &mut |_| {});
        assert!(
            !s.report.colour_textured,
            "with no atlas the colour term can only restate the material term"
        );
    }

    #[test]
    fn the_suggested_level_lands_on_the_painted_bands() {
        let bands = 4;
        let s = segment(&painted(bands), &SegmentOptions::default(), &mut |_| {});
        assert!(s.report.colour_textured);
        assert!(
            s.report.suggested >= 2 && s.report.suggested <= bands + 2,
            "expected roughly {bands} groups, got {}",
            s.report.suggested
        );
    }

    #[test]
    fn cutting_at_the_band_count_separates_the_ends() {
        let bands = 4;
        let m = painted(bands);
        let s = segment(&m, &SegmentOptions::default(), &mut |_| {});
        let cut = s.dendrogram.cut(bands);
        let d = &s.dendrogram;
        let first = cut[d.super_of_face[0] as usize];
        let last = cut[d.super_of_face[m.triangle_count() - 1] as usize];
        assert_ne!(first, last, "the darkest band is not the lightest one");
    }

    #[test]
    fn every_triangle_lands_in_exactly_one_group() {
        let m = painted(5);
        let s = segment(&m, &SegmentOptions::default(), &mut |_| {});
        let cut = s.dendrogram.cut(3);
        assert_eq!(s.dendrogram.super_of_face.len(), m.triangle_count());
        for &sf in &s.dendrogram.super_of_face {
            assert!((sf as usize) < s.dendrogram.super_count);
            assert!((cut[sf as usize] as usize) < 3);
        }
    }

    #[test]
    fn the_neighbour_table_agrees_with_itself_across_every_shared_edge() {
        // What the shader reads to draw a border. If it disagrees with
        // `super_of_face`, outlines appear on one side of an edge and not the
        // other, which looks like a rendering bug and is a data one.
        let m = painted(4);
        let s = segment(&m, &SegmentOptions::default(), &mut |_| {});
        let adj = Adjacency::build(&m);
        let d = &s.dendrogram;

        for t in 0..m.triangle_count() {
            for k in 0..3 {
                let e = &adj.edges[adj.tri_edges[t][k] as usize];
                let other = match (e.tri[0], e.tri[1]) {
                    (Some(a), Some(b)) if a as usize == t => Some(b),
                    (Some(a), Some(b)) if b as usize == t => Some(a),
                    _ => None,
                };
                match other {
                    Some(o) => assert_eq!(
                        d.nbr_of_face[t][k], d.super_of_face[o as usize],
                        "triangle {t} edge {k} names the wrong neighbour"
                    ),
                    None => assert_eq!(
                        d.nbr_of_face[t][k],
                        u32::MAX,
                        "an open border has no neighbour"
                    ),
                }
            }
        }
    }
}
